import type { Match } from "@/types";

const now = new Date();
const inMinutes = (m: number) => new Date(now.getTime() + m * 60000).toISOString();
const agoMinutes = (m: number) => new Date(now.getTime() - m * 60000).toISOString();

export const MOCK_MATCHES: Match[] = [
  {
    id: "m1",
    tournamentId: "trn1",
    tournamentName: "VCT Champions 2025",
    game: "Valorant",
    status: "live",
    scheduledAt: agoMinutes(42),
    teamA: { id: "t1", name: "Neon Serpents", shortName: "NSP", logoUrl: "/teams/nsp.svg", score: 10, color: "#00FFA3" },
    teamB: { id: "t2", name: "Phantom Wave", shortName: "PWV", logoUrl: "/teams/pwv.svg", score: 8, color: "#8B6FFF" },
    map: "Ascent",
    round: "Quarter-Final",
    viewers: 142800,
    streamUrl: "#",
  },
  {
    id: "m2",
    tournamentId: "trn2",
    tournamentName: "IEM Katowice 2025",
    game: "CS2",
    status: "live",
    scheduledAt: agoMinutes(28),
    teamA: { id: "t3", name: "Azure Blaze", shortName: "AZB", logoUrl: "/teams/azb.svg", score: 14, color: "#00D4FF" },
    teamB: { id: "t4", name: "Dark Matter", shortName: "DKM", logoUrl: "/teams/dkm.svg", score: 11, color: "#FF006E" },
    map: "Mirage",
    round: "Semi-Final",
    viewers: 287400,
    streamUrl: "#",
  },
  {
    id: "m3",
    tournamentId: "trn3",
    tournamentName: "LoL World Championship 2025",
    game: "League of Legends",
    status: "live",
    scheduledAt: agoMinutes(15),
    teamA: { id: "t5", name: "Iron Citadel", shortName: "ICT", logoUrl: "/teams/ict.svg", score: 1, color: "#FFB800" },
    teamB: { id: "t6", name: "Crimson Eclipse", shortName: "CRE", logoUrl: "/teams/cre.svg", score: 2, color: "#FF4444" },
    round: "Grand Final Game 3",
    viewers: 524100,
    streamUrl: "#",
  },
  {
    id: "m4",
    tournamentId: "trn4",
    tournamentName: "The International 2025",
    game: "Dota 2",
    status: "upcoming",
    scheduledAt: inMinutes(35),
    teamA: { id: "t7", name: "Void Walkers", shortName: "VDW", logoUrl: "/teams/vdw.svg", score: 0, color: "#9333EA" },
    teamB: { id: "t8", name: "Storm Protocol", shortName: "STP", logoUrl: "/teams/stp.svg", score: 0, color: "#06B6D4" },
    round: "Upper Bracket Final",
    viewers: 0,
    streamUrl: "#",
  },
  {
    id: "m5",
    tournamentId: "trn1",
    tournamentName: "VCT Champions 2025",
    game: "Valorant",
    status: "upcoming",
    scheduledAt: inMinutes(90),
    teamA: { id: "t10", name: "Stellar Collapse", shortName: "STC", logoUrl: "/teams/stc.svg", score: 0, color: "#EC4899" },
    teamB: { id: "t2", name: "Phantom Wave", shortName: "PWV", logoUrl: "/teams/pwv.svg", score: 0, color: "#8B6FFF" },
    round: "Quarter-Final",
    viewers: 0,
    streamUrl: "#",
  },
  {
    id: "m6",
    tournamentId: "trn5",
    tournamentName: "ALGS Pro League S3",
    game: "Apex Legends",
    status: "upcoming",
    scheduledAt: inMinutes(145),
    teamA: { id: "t9", name: "Ghost Protocol", shortName: "GPR", logoUrl: "/teams/gpr.svg", score: 0, color: "#F59E0B" },
    teamB: { id: "t4", name: "Dark Matter", shortName: "DKM", logoUrl: "/teams/dkm.svg", score: 0, color: "#FF006E" },
    round: "Group Stage",
    viewers: 0,
    streamUrl: "#",
  },
  {
    id: "m7",
    tournamentId: "trn2",
    tournamentName: "IEM Katowice 2025",
    game: "CS2",
    status: "completed",
    scheduledAt: agoMinutes(180),
    teamA: { id: "t11", name: "Tungsten Force", shortName: "TGF", logoUrl: "/teams/tgf.svg", score: 16, color: "#10B981" },
    teamB: { id: "t3", name: "Azure Blaze", shortName: "AZB", logoUrl: "/teams/azb.svg", score: 9, color: "#00D4FF" },
    map: "Inferno",
    round: "Quarter-Final",
    viewers: 98200,
  },
  {
    id: "m8",
    tournamentId: "trn3",
    tournamentName: "LoL World Championship 2025",
    game: "League of Legends",
    status: "completed",
    scheduledAt: agoMinutes(240),
    teamA: { id: "t6", name: "Crimson Eclipse", shortName: "CRE", logoUrl: "/teams/cre.svg", score: 3, color: "#FF4444" },
    teamB: { id: "t12", name: "Nexus Rising", shortName: "NXR", logoUrl: "/teams/nxr.svg", score: 0, color: "#3B82F6" },
    round: "Semi-Final",
    viewers: 412300,
  },
  {
    id: "m9",
    tournamentId: "trn1",
    tournamentName: "VCT Champions 2025",
    game: "Valorant",
    status: "completed",
    scheduledAt: agoMinutes(300),
    teamA: { id: "t1", name: "Neon Serpents", shortName: "NSP", logoUrl: "/teams/nsp.svg", score: 13, color: "#00FFA3" },
    teamB: { id: "t10", name: "Stellar Collapse", shortName: "STC", logoUrl: "/teams/stc.svg", score: 7, color: "#EC4899" },
    map: "Bind",
    round: "Round of 16",
    viewers: 76500,
  },
];
