import type { Player } from "@/types";

const genHistory = (games: number, baseKda: number, baseRating: number, winRate: number) => {
  const opponents = [
    "Phantom Wave", "Neon Serpents", "Azure Blaze", "Dark Matter",
    "Iron Citadel", "Crimson Eclipse", "Void Walkers", "Storm Protocol",
    "Ghost Protocol", "Stellar Collapse",
  ];
  return Array.from({ length: games }, (_, i) => {
    const variance = () => (Math.random() - 0.5) * 0.8;
    const date = new Date(Date.now() - (games - i) * 3 * 24 * 60 * 60 * 1000);
    return {
      date: date.toISOString().split("T")[0],
      kda: Math.max(0.5, parseFloat((baseKda + variance()).toFixed(2))),
      rating: Math.max(0.6, parseFloat((baseRating + variance() * 0.3).toFixed(2))),
      win: Math.random() < winRate / 100,
      opponent: opponents[Math.floor(Math.random() * opponents.length)],
    };
  });
};

export const MOCK_PLAYERS: Player[] = [
  {
    id: "p1",
    name: "ZeroCool",
    realName: "Tyler Morrison",
    teamId: "t1",
    role: "Duelist",
    nationality: "US",
    age: 22,
    avatarUrl: "/avatars/p1.svg",
    stats: {
      kills: 847,
      deaths: 312,
      assists: 234,
      kda: 3.47,
      winRate: 78.5,
      headshots: 62.4,
      rating: 1.48,
      gamesPlayed: 60,
      topAgent: "Jett",
    },
    history: genHistory(20, 3.47, 1.48, 78.5),
  },
  {
    id: "p2",
    name: "NightOwl",
    realName: "Sophia Chen",
    teamId: "t1",
    role: "Controller",
    nationality: "US",
    age: 20,
    avatarUrl: "/avatars/p2.svg",
    stats: {
      kills: 512,
      deaths: 298,
      assists: 489,
      kda: 3.36,
      winRate: 76.2,
      headshots: 45.2,
      rating: 1.32,
      gamesPlayed: 60,
      topAgent: "Omen",
    },
    history: genHistory(20, 3.36, 1.32, 76.2),
  },
  {
    id: "p3",
    name: "Phantom_X",
    realName: "Carlos Reyes",
    teamId: "t1",
    role: "Sentinel",
    nationality: "MX",
    age: 24,
    avatarUrl: "/avatars/p3.svg",
    stats: {
      kills: 634,
      deaths: 340,
      assists: 312,
      kda: 2.78,
      winRate: 74.1,
      headshots: 58.7,
      rating: 1.29,
      gamesPlayed: 60,
      topAgent: "Cypher",
    },
    history: genHistory(20, 2.78, 1.29, 74.1),
  },
  {
    id: "p4",
    name: "BlitzRush",
    realName: "Ethan Park",
    teamId: "t1",
    role: "Initiator",
    nationality: "KR",
    age: 19,
    avatarUrl: "/avatars/p4.svg",
    stats: {
      kills: 598,
      deaths: 367,
      assists: 421,
      kda: 2.78,
      winRate: 72.3,
      headshots: 49.1,
      rating: 1.25,
      gamesPlayed: 60,
      topAgent: "Sova",
    },
    history: genHistory(20, 2.78, 1.25, 72.3),
  },
  {
    id: "p5",
    name: "IceBreaker",
    realName: "Liam O'Brien",
    teamId: "t1",
    role: "Flex",
    nationality: "IE",
    age: 23,
    avatarUrl: "/avatars/p5.svg",
    stats: {
      kills: 712,
      deaths: 356,
      assists: 289,
      kda: 2.81,
      winRate: 71.8,
      headshots: 55.3,
      rating: 1.27,
      gamesPlayed: 60,
      topAgent: "Reyna",
    },
    history: genHistory(20, 2.81, 1.27, 71.8),
  },
  {
    id: "p6",
    name: "VortexEU",
    realName: "Magnus Lindqvist",
    teamId: "t2",
    role: "Duelist",
    nationality: "SE",
    age: 21,
    avatarUrl: "/avatars/p6.svg",
    stats: {
      kills: 789,
      deaths: 334,
      assists: 198,
      kda: 2.96,
      winRate: 72.1,
      headshots: 60.8,
      rating: 1.41,
      gamesPlayed: 57,
      topAgent: "Neon",
    },
    history: genHistory(20, 2.96, 1.41, 72.1),
  },
  {
    id: "p7",
    name: "Torrent",
    realName: "Antoine Dubois",
    teamId: "t2",
    role: "Controller",
    nationality: "FR",
    age: 22,
    avatarUrl: "/avatars/p7.svg",
    stats: {
      kills: 478,
      deaths: 289,
      assists: 534,
      kda: 3.49,
      winRate: 69.8,
      headshots: 41.2,
      rating: 1.28,
      gamesPlayed: 57,
      topAgent: "Viper",
    },
    history: genHistory(20, 3.49, 1.28, 69.8),
  },
  {
    id: "p11",
    name: "s1nk",
    realName: "Viktor Johansson",
    teamId: "t3",
    role: "Entry Fragger",
    nationality: "SE",
    age: 23,
    avatarUrl: "/avatars/p11.svg",
    stats: {
      kills: 1243,
      deaths: 467,
      assists: 198,
      kda: 3.08,
      winRate: 81.2,
      headshots: 67.4,
      rating: 1.52,
      gamesPlayed: 69,
      topAgent: "AWP",
    },
    history: genHistory(20, 3.08, 1.52, 81.2),
  },
  {
    id: "p12",
    name: "h4rdline",
    realName: "Mikkel Andersen",
    teamId: "t3",
    role: "IGL",
    nationality: "DK",
    age: 26,
    avatarUrl: "/avatars/p12.svg",
    stats: {
      kills: 987,
      deaths: 512,
      assists: 423,
      kda: 2.75,
      winRate: 79.4,
      headshots: 58.9,
      rating: 1.38,
      gamesPlayed: 69,
      topAgent: "Rifle",
    },
    history: genHistory(20, 2.75, 1.38, 79.4),
  },
  {
    id: "p13",
    name: "fl1ck",
    realName: "Andrei Popescu",
    teamId: "t3",
    role: "AWPer",
    nationality: "RO",
    age: 20,
    avatarUrl: "/avatars/p13.svg",
    stats: {
      kills: 1089,
      deaths: 423,
      assists: 145,
      kda: 2.92,
      winRate: 80.6,
      headshots: 72.1,
      rating: 1.49,
      gamesPlayed: 69,
    },
    history: genHistory(20, 2.92, 1.49, 80.6),
  },
  {
    id: "p21",
    name: "KingSlayer",
    realName: "Jonas Weber",
    teamId: "t5",
    role: "Top Laner",
    nationality: "DE",
    age: 22,
    avatarUrl: "/avatars/p21.svg",
    stats: {
      kills: 823,
      deaths: 312,
      assists: 567,
      kda: 4.46,
      winRate: 70.8,
      headshots: 0,
      rating: 8.4,
      gamesPlayed: 48,
      topChampion: "Darius",
    },
    history: genHistory(20, 4.46, 8.4, 70.8),
  },
  {
    id: "p22",
    name: "JungleProwl",
    realName: "Nina Kovač",
    teamId: "t5",
    role: "Jungler",
    nationality: "HR",
    age: 21,
    avatarUrl: "/avatars/p22.svg",
    stats: {
      kills: 712,
      deaths: 289,
      assists: 698,
      kda: 4.87,
      winRate: 68.9,
      headshots: 0,
      rating: 8.1,
      gamesPlayed: 48,
      topChampion: "Lee Sin",
    },
    history: genHistory(20, 4.87, 8.1, 68.9),
  },
  {
    id: "p26",
    name: "DragonHeart",
    realName: "Park Minho",
    teamId: "t6",
    role: "Mid Laner",
    nationality: "KR",
    age: 20,
    avatarUrl: "/avatars/p26.svg",
    stats: {
      kills: 1045,
      deaths: 234,
      assists: 789,
      kda: 7.84,
      winRate: 83.3,
      headshots: 0,
      rating: 9.2,
      gamesPlayed: 60,
      topChampion: "Zed",
    },
    history: genHistory(20, 7.84, 9.2, 83.3),
  },
  {
    id: "p31",
    name: "Shadow_D2",
    realName: "Pavel Kuznetsov",
    teamId: "t7",
    role: "Carry",
    nationality: "RU",
    age: 24,
    avatarUrl: "/avatars/p31.svg",
    stats: {
      kills: 978,
      deaths: 423,
      assists: 612,
      kda: 3.77,
      winRate: 68.9,
      headshots: 0,
      rating: 7.8,
      gamesPlayed: 61,
      topChampion: "Phantom Assassin",
    },
    history: genHistory(20, 3.77, 7.8, 68.9),
  },
];
