import type { Team } from "@/types";

export const MOCK_TEAMS: Team[] = [
  {
    id: "t1",
    name: "Neon Serpents",
    shortName: "NSP",
    logoUrl: "/teams/nsp.svg",
    game: "Valorant",
    region: "NA",
    rank: 1,
    winRate: 78.5,
    wins: 47,
    losses: 13,
    prize: 250000,
    players: ["p1", "p2", "p3", "p4", "p5"],
    color: "#00FFA3",
    founded: 2021,
    coach: "Dmitri 'Coach_D' Volkov",
  },
  {
    id: "t2",
    name: "Phantom Wave",
    shortName: "PWV",
    logoUrl: "/teams/pwv.svg",
    game: "Valorant",
    region: "EU",
    rank: 2,
    winRate: 72.1,
    wins: 41,
    losses: 16,
    prize: 185000,
    players: ["p6", "p7", "p8", "p9", "p10"],
    color: "#8B6FFF",
    founded: 2020,
    coach: "Lucas 'Tactic' Ferreira",
  },
  {
    id: "t3",
    name: "Azure Blaze",
    shortName: "AZB",
    logoUrl: "/teams/azb.svg",
    game: "CS2",
    region: "EU",
    rank: 1,
    winRate: 81.2,
    wins: 56,
    losses: 13,
    prize: 420000,
    players: ["p11", "p12", "p13", "p14", "p15"],
    color: "#00D4FF",
    founded: 2019,
    coach: "Erik 'ErrikzZ' Gustafsson",
  },
  {
    id: "t4",
    name: "Dark Matter",
    shortName: "DKM",
    logoUrl: "/teams/dkm.svg",
    game: "CS2",
    region: "NA",
    rank: 3,
    winRate: 65.4,
    wins: 38,
    losses: 20,
    prize: 130000,
    players: ["p16", "p17", "p18", "p19", "p20"],
    color: "#FF006E",
    founded: 2022,
    coach: "Marcus 'Viper' Cole",
  },
  {
    id: "t5",
    name: "Iron Citadel",
    shortName: "ICT",
    logoUrl: "/teams/ict.svg",
    game: "League of Legends",
    region: "EU",
    rank: 2,
    winRate: 70.8,
    wins: 34,
    losses: 14,
    prize: 310000,
    players: ["p21", "p22", "p23", "p24", "p25"],
    color: "#FFB800",
    founded: 2018,
    coach: "Yohan 'Mastermind' Park",
  },
  {
    id: "t6",
    name: "Crimson Eclipse",
    shortName: "CRE",
    logoUrl: "/teams/cre.svg",
    game: "League of Legends",
    region: "APAC",
    rank: 1,
    winRate: 83.3,
    wins: 50,
    losses: 10,
    prize: 490000,
    players: ["p26", "p27", "p28", "p29", "p30"],
    color: "#FF4444",
    founded: 2017,
    coach: "Kim 'Architect' Seojun",
  },
  {
    id: "t7",
    name: "Void Walkers",
    shortName: "VDW",
    logoUrl: "/teams/vdw.svg",
    game: "Dota 2",
    region: "CIS",
    rank: 2,
    winRate: 68.9,
    wins: 42,
    losses: 19,
    prize: 280000,
    players: ["p31", "p32", "p33", "p34", "p35"],
    color: "#9333EA",
    founded: 2020,
    coach: "Alexei 'Shadow' Petrov",
  },
  {
    id: "t8",
    name: "Storm Protocol",
    shortName: "STP",
    logoUrl: "/teams/stp.svg",
    game: "Dota 2",
    region: "APAC",
    rank: 1,
    winRate: 76.2,
    wins: 48,
    losses: 15,
    prize: 350000,
    players: ["p36", "p37", "p38", "p39", "p40"],
    color: "#06B6D4",
    founded: 2019,
    coach: "Wei 'Dragon' Liu",
  },
  {
    id: "t9",
    name: "Ghost Protocol",
    shortName: "GPR",
    logoUrl: "/teams/gpr.svg",
    game: "Apex Legends",
    region: "NA",
    rank: 1,
    winRate: 74.5,
    wins: 35,
    losses: 12,
    prize: 175000,
    players: ["p41", "p42", "p43"],
    color: "#F59E0B",
    founded: 2021,
    coach: "Jamal 'Fury' Washington",
  },
  {
    id: "t10",
    name: "Stellar Collapse",
    shortName: "STC",
    logoUrl: "/teams/stc.svg",
    game: "Valorant",
    region: "APAC",
    rank: 3,
    winRate: 61.7,
    wins: 29,
    losses: 18,
    prize: 95000,
    players: ["p44", "p45", "p46", "p47", "p48"],
    color: "#EC4899",
    founded: 2022,
    coach: "Ryo 'Sage' Nakamura",
  },
  {
    id: "t11",
    name: "Tungsten Force",
    shortName: "TGF",
    logoUrl: "/teams/tgf.svg",
    game: "CS2",
    region: "SA",
    rank: 1,
    winRate: 69.3,
    wins: 43,
    losses: 19,
    prize: 145000,
    players: ["p49", "p50", "p51", "p52", "p53"],
    color: "#10B981",
    founded: 2020,
    coach: "Felipe 'Furia' Santos",
  },
  {
    id: "t12",
    name: "Nexus Rising",
    shortName: "NXR",
    logoUrl: "/teams/nxr.svg",
    game: "League of Legends",
    region: "NA",
    rank: 3,
    winRate: 58.2,
    wins: 25,
    losses: 18,
    prize: 88000,
    players: ["p54", "p55", "p56", "p57", "p58"],
    color: "#3B82F6",
    founded: 2021,
    coach: "Brandon 'Strat' Miller",
  },
];
